-- Diese Datei ist absichtlich linter-neutral gehalten.
--
-- Hintergrund:
-- Die VS Code MSSQL-Validierung interpretiert SQLite-Syntax in *.sql Dateien
-- als T-SQL und erzeugt dadurch falsche Syntaxfehler.
--
-- Bitte das eigentliche SQLite-Skript ausfuehren:
--   scripts/sql/backfill_usd_paypal_fee.sqlite
--
-- Ausfuehrung:
--   sqlite3 -header -column /path/to/arrow_ops.db < scripts/sql/backfill_usd_paypal_fee.sqlite
