-- Diese Datei ist absichtlich linter-neutral gehalten.
--
-- Hintergrund:
-- Die VS Code MSSQL-Validierung interpretiert SQLite-Syntax in *.sql Dateien
-- als T-SQL und erzeugt dadurch falsche Syntaxfehler.
--
-- Bitte das eigentliche SQLite-Skript ausfuehren:
--   scripts/sql/normalize_us_state_city_suffixes.sqlite
--
-- Ausfuehrung:
--   sqlite3 /pfad/zur/arrow_ops.db < scripts/sql/normalize_us_state_city_suffixes.sqlite
